name: dla
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - matplotlib
  - scikit-learn
  - pillow
  - tqdm
  - jupyterlab
  - pip
  - pip:
      - tensorboard
